from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('index', Index, name='index'),
    path('items', Items, name='items'),
    path('menus', Menus, name='menus'),
    path('orderitem', OrderItem, name='orderitem'),
    path('order', Orders, name='order'),
    path('restaurant', Restaurants, name='restaurant'),
    path('feedback', Feedbacks, name='feedback'),
    path('register', Register, name='register'),
    path('login', Login, name='login'),
    path('payment/', PaymentView.as_view(), name='payment'),
    path('Delete_dataFeed/<int:id>', Delete_dataFeed, name='delete_data_feed'),
    path('Delete_data/<int:id>', Delete_data, name='delete_data'),
    path('Update_data/<int:id>', Update_Data, name='update_data'),
    path('Delete_data1/<int:id>', Delete_data1, name='delete_data1'),
    path('Delete_data2/<int:id>', Delete_data2, name='delete_data2'),
    path('Delete_data3/<int:id>', Delete_data3, name='delete_data3'),
    path('Delete_data4/<int:id>', Delete_data4, name='delete_data4'),
    path('Delete_data5/<int:id>', Delete_data5, name='delete_data5'),
    path('insertdatacust', InsertDataCust, name='insertdatacust'),
    path('insertdataitem', InsertDataItem, name='insertdataitem'),
    path('insertdatares', InsertDataRes, name='insertdatares'),
    path('insertdatamenu', InsertDataMenu, name='insertdatamenu'),
    path('updatedataitem/<int:id>', Update_DataItem, name='updatedataitem'),
    path('updatedatamenu/<int:id>', Update_DataMenu, name='updatedatamenu'),
    path('updatedatares/<int:id>', Update_DataRes, name='updatedatares'),
    path('', Index1, name='index1'),
    path('foodzone', Foodzone, name='foodzone'),
    path('about', About, name='about'),
    path('service', Service, name='service'),
    path('gallery', Gallery, name='gallery'),
    path('contact', contact, name='contact'),
    path('feedback1', Feedback1, name='feedback1'),
    path('forsignup', forsignup, name='forsignup'),
    path('signup1', customerRegister, name='signup1'),
    path('signup2', restaurantsRegister, name='signup2'),
    path('custprofile', customerProfile, name='custprofile'),
    path('createcustomer', CreateCustomer, name='createcustomer'),
    path('updatecustomer/<int:id>', updateCustomer, name='updatecustomer'),
    path('restprofile', restaurantsProfile, name='restprofile'),
    path('createrestaurant', CreateRestaurant.as_view(), name='createrestaurant'),
    path('updaterestaurant/<int:id>', updateRestaurant, name='updaterestaurant'),
    path('login1', Login1, name='login1'),
    path('custlogin', customerLogin, name='custlogin'),
    path('restlogin', restLogin, name='restlogin'),
    #path('restaurantmenu',restaurantMenu, name='restaurantmenu'),
    path('rmenu/<int:pk>/', rMenu, name='rmenu'),
    path('menumanipulation', menuManipulation, name='menumanipulation'),
    path('checkout/', checkOut, name='checkout'),
    path('orderplaced', orderPlaced, name='orderplaced'),
    path('orderlist', orderList, name='orderlist'),
    path('logout', Logout, name='logout'),
    path('reset_password/',
         auth_views.PasswordResetView.as_view(template_name="password_reset.html"),
         name="reset_password"),

    path('reset_password_sent/',
         auth_views.PasswordResetDoneView.as_view(template_name="password_reset_sent.html"),
         name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_form.html"),
         name="password_reset_confirm"),

    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_done.html"),
         name="password_reset_complete"),
    path('custorder',custorder,name='custorder'),

]
